### ISSUE TITLE
Structures are not spawning or just parts of it

### ISSUE THREAD

**Issue by GalaxyS7** [NLBlackEagle/Dregora#21] opened 2019-03-15 22:58 UTC
Minecraft version
Forge 1.12.2 14.23.5.2807

Dregora version
Dregora-1.12.2-v1.5.1 HotFix ( NO-LAG Update )

OTG version
OpenTerrainGenerator-1.12.2 - v6.jar

Environment Type (Forge or Server such as Spigot)
Forge (Singleplayer)

Steps to reproduce the problem

1. install forge

2. put mods in mods folder (all downloaded from Minecraft curse Forge)
-OTG
-Dregora
-just enough items (jei_1.12.2-4.15.0.269.jar)
-journeymap (journeymap-1.12.2-5.5.4)
-Optifine (OptiFine 1.12.2 HD U E3)

3. Start Minecraft

4. Create new world
World settings: world_dregora
-Gamemode: Creative
-Allow cheats: On

I noticed something weird with the Biometable in the OpenTerrainGenerator folder. It looks like it got corrupted by the unzipping procedure. I also tried to unzip it manually and then replace it with the uncorrupted. But it didn't changed anything, even when I created a new world.

I think it could also be an issue with the forge version.

In the meantime I will try to run it with different forge versions and look if it makes a difference.

I will write if I find a solution.

![BiomeTable](https://user-images.githubusercontent.com/26336448/54464341-98654f00-4776-11e9-8a07-c2887af0bcaf.PNG)

[latest.log](https://github.com/NLBlackEagle/Dregora/files/2973022/latest.log)

![Screenshot (23)](https://user-images.githubusercontent.com/26336448/54463765-736fdc80-4774-11e9-9192-e1e6f728884a.png)

![2019-03-15_21 57 12](https://user-images.githubusercontent.com/26336448/54463966-293b2b00-4775-11e9-8b30-651dd5fb3a3e.png)

![2019-03-15_21 57 30](https://user-images.githubusercontent.com/26336448/54463971-30623900-4775-11e9-8118-1c768cea9b55.png)

![2019-03-15_21 57 38](https://user-images.githubusercontent.com/26336448/54463985-3a843780-4775-11e9-9159-ddce6f8088db.png)

![Screenshot (26)](https://user-images.githubusercontent.com/26336448/54465995-2133b900-477e-11e9-8806-b95e171baf1c.png)

**Comment by NLBlackEagle** [comment] 2019-03-18 23:01
Thanks for reporting these issues. I will try to reproduce them and fix them next update which is to release in 2 weeks.

**Comment by alxcool** [comment] 2019-05-22 01:59
I'm glad this issue happen with someone else, because on forge 2768 on a older computer (old launcher) single player, it din't happen. Cheer up, your world and work is more than amazing!

**Comment by NLBlackEagle** [comment] 2019-11-19 09:50
Thanks for the reply! And sorry for the late response, discord webhook has just been fixed so i will be pinged again once a issue comes in! ( This wasnt the case for a pretty long time )

I have confirmed this issue will be fixed as of v1.62 ( perhaps on an earlier build )

**Closed as completed by NLBlackEagle** 2019-11-19 09:50 UTC
Labels: Issue, Forge
